### ISSUE TITLE
`flex_table1()` not saving table to Word when using `filepath` argument

### ISSUE THREAD

**Issue by rempsyc** [Buedenbender/datscience#11]
Hey!

Finally doing my first Table 1 now and I'm planning to use your package :)

Documentation says:
> If a filepath is provided it also creates the respective file (e.g., a word .docx file)

Going through the example, I try to save the file directly without explicitly calling `save_flextable()`:

``` r
packageVersion("datscience")
#> [1] '0.2.6'
library(datscience)

# Comparison of just two Groups
str_formula <- "~ Sepal.Length + Sepal.Width +test | Species"
data <- dplyr::filter(iris, Species %in% c("setosa", "versicolor"))
data$test <- factor(rep(c("Female", "Male"), 50))
table_caption <- c("Table 1", "A test on the Iris Data")
flex_table1(str_formula, data = data, table_caption = table_caption,
            filepath = "test")
```

<img src="https://i.imgur.com/A5IwQOH.png" width="1089" />

<sup>Created on 2023-10-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

But there is no saved file. The argument is not explicit, is it passed through dots? It doesn't seem to be working for me. Thanks

**Comment by Buedenbender** [comment]
Hi Rémi, 

awesome to see the package is tested / used by other people then me. 
Sadly as I fully stopped to develop in R I guess the package is more or less deprecated.

However I was somewhat interested to see why it is not creating the word document (as it is promising)
I gues the documentation is more a wish for the future to be implemented (i.e., the functionality
to directly create the word document is not yet implented). I checked the function https://github.com/Buedenbender/datscience/blob/main/R/flex_table1.R#L608 and as I approach the end of it I realized it is not yet implemented.

To give a solution you can either call `save_flextable()` separetly like this:
```r
ft = flex_table1(str_formula, data = data, table_caption = table_caption)
save_flextable(ft, filepath = "test")
```

OR (if I am really lukcy) you are always more then welcome to implement it and submit a PR / you can also get maintainer rights and directly push it to main if you would be interested. No worries / pressure though I realize how busy you schedule is :)

**Comment by rempsyc** [comment]
That works, thanks!
